### ISSUE TITLE
404 error for the pre-trained model

### ISSUE THREAD

**Issue by chaoqinhuang** [hiyaroy12/DFT_inpainting#1]
Please upload the pre-trained model again or provide other links. Thank you!

**Comment by ofirkris** [comment]
Same issue here.
Also are you planning to release code for "Toward Better Planetary Surface Exploration inpainting"?

**Comment by hiyaroy12** [comment]
@chaoqinhuang @ofirkris The pre-trained models are updated in the README. You can find the models [here](https://drive.google.com/drive/folders/1K4ry5qlkzMzk3ZqrS1sLm4p949ebIXfv).
